version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: .circleci/jobs/bundle-install.sh
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: .circleci/jobs/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-preview:
    branches:
      only:
        - master
        - circle
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: .circleci/jobs/bundle-install.sh
      - run: .circleci/jobs/deploy-preview.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-preview
