version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: .circleci/jobs/bundle-install.sh
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: .circleci/jobs/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-preview:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: .circleci/jobs/bundle-install.sh
      - run: .circleci/jobs/deploy-preview.sh

  deploy-production:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: .circleci/jobs/bundle-install.sh
      - run: .circleci/jobs/deploy-production.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-preview:
          requires:
            - build
          filters:
            branches:
              only: master
      - prod-hold:
          type: approval
          requires:
           - deploy-preview
      - deploy-production:
          requires:
           - prod-hold
